language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "arnclaudel-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"
notifications:
    slack: open-data-talk:mtISmEkmb4mOYBXCJCsWVjWC  
