language: java
jdk: oraclejdk8
notifications:
    slack: open-data-talk:mtISmEkmb4mOYBXCJCsWVjWC
addons:
  sonarcloud:
    organization: "arnclaudel-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
  - "$HOME/.m2"
